# Generated by Django 4.1.6 on 2023-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
